spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mp?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

#logging:
#  level:
#    com.itheima: debug
#  pattern:
#    dateformat: HH:mm:ss


#mybatis:
#  mapper-locations: classpath*:mapper/*.xml

mybatis-plus:
  type-aliases-package: com.itheima.mp.domain.po #包别名
  mapper-locations: classpath:/mapper/**.xml
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰
    cache-enabled: false # 是否开启二级缓存
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启日志打印
  global-config: # 全局配置
    banner: false #打印mp的LOGO
    db-config:
      # 数据库配置
      id-type: auto
